name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@v1
        with:
          deno-version: v1.3.x
      - run: |
          deno fmt **/*.ts --check
          deno test -A
